function val=fun_f(x,t,epsilon)
val=exp(-t).*((exp(-x./epsilon.^(1./2))+exp((x-1)./epsilon.^(1./2)))./(exp(-1./epsilon.^(1./2))+1)-cos(pi.*x).^2)+...
    epsilon.*(exp(-t)-1).*((exp(-x./epsilon.^(1./2))./epsilon+exp((x-1)./epsilon.^(1./2))./epsilon)./(exp(-1./epsilon.^(1./2))+1)-2.*pi.^2.*sin(pi.*x).^2+2.*pi.^2.*cos(pi.*x).^2)...
            -((exp(-x./epsilon.^(1./2))+exp((x-1)./epsilon.^(1./2)))./(exp(-1./epsilon.^(1./2))+1)-cos(pi.*x).^2).*(exp(-t)-1).*(3.*x.^2+2.*x+1);
%% x+1
% val=exp(-t).*((exp(-x./epsilon.^(1./2)) + exp((x - 1)./epsilon.^(1./2)))./(exp(-1./epsilon.^(1./2)) + 1) - cos(pi.*x).^2) + epsilon.*(exp(-t) - 1).*((exp(-x./epsilon.^(1./2))./epsilon + exp((x - 1)./epsilon.^(1./2))./epsilon)./(exp(-1./epsilon.^(1./2)) + 1) - 2.*pi.^2.*sin(pi.*x).^2 + 2.*pi.^2.*cos(pi.*x).^2) - ((exp(-x./epsilon.^(1./2)) + exp((x - 1)./epsilon.^(1./2)))./(exp(-1./epsilon.^(1./2)) + 1) - cos(pi.*x).^2).*(exp(-t) - 1).*(x + 1);

%% exp(x)^(-1)
% val=exp(-t).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1)) +...
%     exp(-t).*(x.*(x - 1) - 1).*(exp(-1/epsilon) + exp((x - 1)/epsilon)/epsilon - 1) -...
%     exp(-t).*exp(-x).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1)) + (exp(-t).*exp((x - 1)/epsilon))/epsilon;
%% exp(x)
% val=exp(-t).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1)) +...
%     exp(-t).*(x.*(x - 1) - 1).*(exp(-1/epsilon) + exp((x - 1)/epsilon)/epsilon - 1) +...
%     (exp(-t).*exp((x - 1)/epsilon))/epsilon - exp(-t).*exp(x).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1));
%% x
% val=exp(-t).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1)) +...
%     exp(-t).*(x.*(x - 1) - 1).*(exp(-1/epsilon) + exp((x - 1)/epsilon)/epsilon - 1) -...
%     x.*exp(-t).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1)) + (exp(-t).*exp((x - 1)/epsilon))/epsilon;
%% 10+sin(x)

% val=exp(-t).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1)) +...
%     exp(-t).*(x.*(x - 1) - 1).*(exp(-1/epsilon) + exp((x - 1)/epsilon)/epsilon - 1) -...
%     exp(-t).*(sin(x) + 10).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1)) + (exp(-t).*exp((x - 1)/epsilon))/epsilon;
%% 10+0.5*sin(x)+0.5*cos(x)
% val=exp(-t).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x*(exp(-1/epsilon) - 1)) +...
%     exp(-t).*(x.*(x - 1) - 1).*(exp(-1/epsilon) + exp((x - 1)/epsilon)/epsilon - 1) +...
%     (exp(-t).*exp((x - 1)/epsilon))/epsilon - exp(-t).*(exp((x - 1)/epsilon) - exp(-1/epsilon) + x.*(exp(-1/epsilon) - 1)).*(cos(x)/2 + sin(x)/2 + 10);
end